const main = async (): Promise<void> => {};
main().catch((error) => {
  console.log(error);
  process.exit(-1);
});
